# Generated by Django 3.2.5 on 2021-07-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksHistroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_companyName', models.CharField(max_length=100)),
                ('_date', models.DateField()),
                ('_open', models.DecimalField(decimal_places=7, max_digits=10)),
                ('_high', models.DecimalField(decimal_places=7, max_digits=10)),
                ('_low', models.DecimalField(decimal_places=7, max_digits=10)),
                ('_close', models.DecimalField(decimal_places=7, max_digits=10)),
                ('_adjacentClose', models.DecimalField(decimal_places=7, max_digits=10)),
                ('_volume', models.IntegerField()),
            ],
        ),
    ]
