# Generated by Django 3.2.5 on 2021-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarChart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockshistroy',
            name='_adjacentClose',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockshistroy',
            name='_close',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockshistroy',
            name='_high',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockshistroy',
            name='_low',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockshistroy',
            name='_open',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
