# Generated by Django 3.2.5 on 2021-07-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarChart', '0002_auto_20210722_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockshistroy',
            name='_volume',
            field=models.BigIntegerField(),
        ),
    ]
