# Generated by Django 3.2.5 on 2021-07-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarChart', '0003_alter_stockshistroy__volume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StocksHistroy',
            new_name='StocksHistory',
        ),
    ]
