# Generated by Django 3.2.5 on 2021-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarChart', '0004_rename_stockshistroy_stockshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockshistory',
            name='_adjacentClose',
            field=models.DecimalField(decimal_places=7, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='_close',
            field=models.DecimalField(decimal_places=7, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='_high',
            field=models.DecimalField(decimal_places=7, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='_low',
            field=models.DecimalField(decimal_places=7, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='_open',
            field=models.DecimalField(decimal_places=7, max_digits=14),
        ),
    ]
